### ISSUE TITLE
EBNF Specification for FPL

### ISSUE THREAD

**Issue by JeffLansing** [bookofproofs/fpl#1]
There is no *one* EBNF, so planning to write unambiguous specification language using 'EBNF' is a road to failure, unless you choose carefully. Probably the safest choice is W3C EBNF.

**Comment by bookofproofs** [comment]
Thank you for the hint. I noticed already. The EBNF is a dialect, in fact, a dialect used by the TatSu python package so we can generate a parser automatically.
